#include "wifi_tostr.h"

char const *wifi_event_tostr(wifi_event_t event)
{
	switch (event) {
	case WIFI_EVENT_WIFI_READY:
		return "WIFI_EVENT_WIFI_READY";
	case WIFI_EVENT_SCAN_DONE:
		return "WIFI_EVENT_SCAN_DONE";
	case WIFI_EVENT_STA_START:
		return "WIFI_EVENT_STA_START";
	case WIFI_EVENT_STA_STOP:
		return "WIFI_EVENT_STA_STOP";
	case WIFI_EVENT_STA_CONNECTED:
		return "WIFI_EVENT_STA_CONNECTED";
	case WIFI_EVENT_STA_DISCONNECTED:
		return "WIFI_EVENT_STA_DISCONNECTED";
	case WIFI_EVENT_STA_AUTHMODE_CHANGE:
		return "WIFI_EVENT_STA_AUTHMODE_CHANGE";
	case WIFI_EVENT_STA_WPS_ER_SUCCESS:
		return "WIFI_EVENT_STA_WPS_ER_SUCCESS";
	case WIFI_EVENT_STA_WPS_ER_FAILED:
		return "WIFI_EVENT_STA_WPS_ER_FAILED";
	case WIFI_EVENT_STA_WPS_ER_TIMEOUT:
		return "WIFI_EVENT_STA_WPS_ER_TIMEOUT";
	case WIFI_EVENT_STA_WPS_ER_PIN:
		return "WIFI_EVENT_STA_WPS_ER_PIN";
	case WIFI_EVENT_STA_WPS_ER_PBC_OVERLAP:
		return "WIFI_EVENT_STA_WPS_ER_PBC_OVERLAP";
	case WIFI_EVENT_AP_START:
		return "WIFI_EVENT_AP_START";
	case WIFI_EVENT_AP_STOP:
		return "WIFI_EVENT_AP_STOP";
	case WIFI_EVENT_AP_STACONNECTED:
		return "WIFI_EVENT_AP_STACONNECTED";
	case WIFI_EVENT_AP_STADISCONNECTED:
		return "WIFI_EVENT_AP_STADISCONNECTED";
	case WIFI_EVENT_AP_PROBEREQRECVED:
		return "WIFI_EVENT_AP_PROBEREQRECVED";
	case WIFI_EVENT_FTM_REPORT:
		return "WIFI_EVENT_FTM_REPORT";
	case WIFI_EVENT_STA_BSS_RSSI_LOW:
		return "WIFI_EVENT_STA_BSS_RSSI_LOW";
	case WIFI_EVENT_ACTION_TX_STATUS:
		return "WIFI_EVENT_ACTION_TX_STATUS";
	case WIFI_EVENT_ROC_DONE:
		return "WIFI_EVENT_ROC_DONE";
	case WIFI_EVENT_STA_BEACON_TIMEOUT:
		return "WIFI_EVENT_STA_BEACON_TIMEOUT";
	case WIFI_EVENT_CONNECTIONLESS_MODULE_WAKE_INTERVAL_START:
		return "WIFI_EVENT_CONNECTIONLESS_MODULE_WAKE_INTERVAL_START";
	case WIFI_EVENT_AP_WPS_RG_SUCCESS:
		return "WIFI_EVENT_AP_WPS_RG_SUCCESS";
	case WIFI_EVENT_AP_WPS_RG_FAILED:
		return "WIFI_EVENT_AP_WPS_RG_FAILED";
	case WIFI_EVENT_AP_WPS_RG_TIMEOUT:
		return "WIFI_EVENT_AP_WPS_RG_TIMEOUT";
	case WIFI_EVENT_AP_WPS_RG_PIN:
		return "WIFI_EVENT_AP_WPS_RG_PIN";
	case WIFI_EVENT_AP_WPS_RG_PBC_OVERLAP:
		return "WIFI_EVENT_AP_WPS_RG_PBC_OVERLAP";
	case WIFI_EVENT_ITWT_SETUP:
		return "WIFI_EVENT_ITWT_SETUP";
	case WIFI_EVENT_ITWT_TEARDOWN:
		return "WIFI_EVENT_ITWT_TEARDOWN";
	case WIFI_EVENT_ITWT_PROBE:
		return "WIFI_EVENT_ITWT_PROBE";
	case WIFI_EVENT_ITWT_SUSPEND:
		return "WIFI_EVENT_ITWT_SUSPEND";
	case WIFI_EVENT_TWT_WAKEUP:
		return "WIFI_EVENT_TWT_WAKEUP";
	case WIFI_EVENT_BTWT_SETUP:
		return "WIFI_EVENT_BTWT_SETUP";
	case WIFI_EVENT_BTWT_TEARDOWN:
		return "WIFI_EVENT_BTWT_TEARDOWN";
	case WIFI_EVENT_NAN_STARTED:
		return "WIFI_EVENT_NAN_STARTED";
	case WIFI_EVENT_NAN_STOPPED:
		return "WIFI_EVENT_NAN_STOPPED";
	case WIFI_EVENT_NAN_SVC_MATCH:
		return "WIFI_EVENT_NAN_SVC_MATCH";
	case WIFI_EVENT_NAN_REPLIED:
		return "WIFI_EVENT_NAN_REPLIED";
	case WIFI_EVENT_NAN_RECEIVE:
		return "WIFI_EVENT_NAN_RECEIVE";
	case WIFI_EVENT_NDP_INDICATION:
		return "WIFI_EVENT_NDP_INDICATION";
	case WIFI_EVENT_NDP_CONFIRM:
		return "WIFI_EVENT_NDP_CONFIRM";
	case WIFI_EVENT_NDP_TERMINATED:
		return "WIFI_EVENT_NDP_TERMINATED";
	case WIFI_EVENT_HOME_CHANNEL_CHANGE:
		return "WIFI_EVENT_HOME_CHANNEL_CHANGE";
	case WIFI_EVENT_STA_NEIGHBOR_REP:
		return "WIFI_EVENT_STA_NEIGHBOR_REP";
	case WIFI_EVENT_AP_WRONG_PASSWORD:
		return "WIFI_EVENT_AP_WRONG_PASSWORD";
	default:
		return "UNKNOWN_WIFI_EVENT";
	}
}

char const *wifi_auth_mode_str(wifi_auth_mode_t authmode)
{
	switch (authmode) {
	case WIFI_AUTH_OPEN:
		return "OPEN";
	case WIFI_AUTH_OWE:
		return "OWE";
	case WIFI_AUTH_WEP:
		return "WEP";
	case WIFI_AUTH_WPA_PSK:
		return "WPA_PSK";
	case WIFI_AUTH_WPA2_PSK:
		return "WPA2_PSK";
	case WIFI_AUTH_WPA_WPA2_PSK:
		return "WPA_WPA2_PSK";
	case WIFI_AUTH_ENTERPRISE:
		return "ENTERPRISE";
	case WIFI_AUTH_WPA3_PSK:
		return "WPA3_PSK";
	case WIFI_AUTH_WPA2_WPA3_PSK:
		return "WPA2_WPA3_PSK";
	case WIFI_AUTH_WPA3_ENT_192:
		return "WPA3_ENT_192";
	default:
		return "UNKNOWN";
	}
}

char const *wifi_cipher_type_str(wifi_cipher_type_t type)
{
	switch (type) {
	case WIFI_CIPHER_TYPE_NONE:
		return "NONE";
	case WIFI_CIPHER_TYPE_WEP40:
		return "WEP40";
	case WIFI_CIPHER_TYPE_WEP104:
		return "WEP104";
	case WIFI_CIPHER_TYPE_TKIP:
		return "TKIP";
	case WIFI_CIPHER_TYPE_CCMP:
		return "CCMP";
	case WIFI_CIPHER_TYPE_TKIP_CCMP:
		return "TKIP_CCMP";
	case WIFI_CIPHER_TYPE_AES_CMAC128:
		return "AES_CMAC128";
	case WIFI_CIPHER_TYPE_SMS4:
		return "SMS4";
	case WIFI_CIPHER_TYPE_GCMP:
		return "GCMP";
	case WIFI_CIPHER_TYPE_GCMP256:
		return "GCMP256";
	default:
		return "UNKNOWN";
	}
}